# Generated by Django 3.0.5 on 2020-04-26 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Figures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TracingOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trace', models.CharField(max_length=10)),
                ('enable', models.BooleanField(default=False)),
                ('smoothing', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lng', models.FloatField()),
                ('lat', models.FloatField()),
                ('figure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='app.Figures')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('originalName', models.CharField(max_length=30)),
                ('link', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d')),
                ('externalLink', models.CharField(max_length=100)),
                ('localPath', models.CharField(max_length=100)),
                ('labeled', models.BooleanField(default=False)),
                ('lastEdited', models.DateField()),
                ('labelData', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Projects')),
            ],
        ),
        migrations.CreateModel(
            name='FormPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=22)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='app.Projects')),
            ],
        ),
        migrations.AddField(
            model_name='figures',
            name='formId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.FormPart'),
        ),
        migrations.AddField(
            model_name='figures',
            name='imageFigures',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imageFigures', to='app.Images'),
        ),
        migrations.AddField(
            model_name='figures',
            name='tracingOptions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.TracingOptions'),
        ),
    ]
